### ISSUE TITLE
Payment Processor: Not enough funds to cover the tx fees for sending out payments, decreasing rewards by ... and retrying

### ISSUE THREAD

**Issue by aayanl** [joshuayabut/z-nomp#5]
It kept doing this till it got to 100% and stopped 
http://imgur.com/EzlynsX

**Comment by aayanl** [comment]
Could it be because the pool doesn't send the coins to a ZAddress? https://github.com/zcash/zcash/wiki/Mining-Guide

**Comment by aayanl** [comment]
I think it might also be that the pool pays the transaction fees out of its own pocket instead of the block reward 

```
    // generate the fees and coinbase tx
    fees = [];
    rpcData.transactions.forEach(function(value) {
        fees.push(value);
    });
this.reward = transactions.getFees(fees) + 1250000000;

```

**Comment by aayanl** [comment]
Nope, neither way worked.

**Comment by joshuayabut** [comment]
I looked into this and it fails because the entirety of a block's coinbase rewards need to be sent to a z_address before they can be sent to a t_address.

I think the easiest way to fix this is to add a subroutine to send to a z_address and then back to the pool's t_address.

I'm taking a few days off from work so I'll be able to get it done this week.

**Comment by joshuayabut** [comment]
Currently undergoing testing.
